### ISSUE TITLE
Wait what? The code has no translation yet says to go ahead and deploy?

### ISSUE THREAD

**Issue by TsunayoshiSawada** [Dubzer/TgTranslator#11]
![image](https://user-images.githubusercontent.com/34431649/149938513-88c863d4-39d1-4b72-bb27-1fc6df5e9fed.png)
![image](https://user-images.githubusercontent.com/34431649/149938541-345033c9-3a34-41e6-b9af-b6ee709d0fa9.png)
![image](https://user-images.githubusercontent.com/34431649/149938565-2eeeb13d-bee7-4acd-bddf-382f01759855.png)

There is nothing on the repo that actually makes this the same code that is deployed. 
Why not at least mention this somewhere on readme that is this is less than half of the source code?

**Comment by Dubzer** [comment]
> There is nothing on the repo that actually makes this the same code that is deployed.

I don't quite understand why is this a problem. Can you expand your question?
