### ISSUE TITLE
No translation between Two similar language 

### ISSUE THREAD

**Issue by hesperhu** [Dubzer/TgTranslator#17]
I have a telegram group that has people spoken in two languages, there is no need translating from one to another. Will you please add some features to support this scenario? For instance, Simplified Chinese and Traditional  Chinese, there is no need translating from Traditional Chinese to Simplified Chinese, coz all people can read those two languages.

**Comment by Dubzer** [comment]
hi! thanks for reporting. it was fixed with the latest update
