### ISSUE TITLE
Translate targeted messages

### ISSUE THREAD

**Issue by ultimateshadsform** [Dubzer/TgTranslator#19]
Would be nice to be able to translate a message manually. Like tagging the bot to a reply or something.

Example: Reply to message you want to translate and then @ the translate bot.

**Comment by Dubzer** [comment]
Hello!
There's a manual mode in the settings, which does exactly that 
![image](https://github.com/user-attachments/assets/3ef1f8d7-0fe3-4237-a8f4-e36d1be41e0a)

**Comment by ultimateshadsform** [comment]
Thank you!
