### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by SamAriafar** [Dubzer/TgTranslator#5]
I'm trying to build this on a Linux machine (Ubuntu 18.04), but I'm receiving the error below:

root@sam:/var/www/TelegramGroupTranslatorBot# dotnet publish -c Release
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 1.85 sec for /var/www/TelegramGroupTranslatorBot/src/TgTranslator.csproj.
Extensions/IServiceCollectionExtensions.cs(81,28): error CS7036: There is no argument given that corresponds to the required formal parameter 'validator' of 'MessageHandler.MessageHandler(TelegramBotClient, BotMenu, SettingsProcessor, ILanguageDetector, ITranslator, IMetrics, Blacklist, MessageValidator)' [/var/www/TelegramGroupTranslatorBot/src/TgTranslator.csproj]
SettingsProcessor.cs(59,80): warning CS8509: The switch expression does not handle all possible inputs (it is not exhaustive). [/var/www/TelegramGroupTranslatorBot/src/TgTranslator.csproj]

**Comment by Dubzer** [comment]
Hi. Thank you for reporting this issue. I'm about to release a big update of the repository, and it will be fixed, so stay tuned

**Comment by Dubzer** [comment]
It was fixed in the last commit, thanks for the help! If you have any questions, feel free to open new issues
