### ISSUE TITLE
Build error on CentOS 7.x

### ISSUE THREAD

**Issue by SamAriafar** [Dubzer/TgTranslator#6]
First of all, you need to update the documentation (readme.md file) and change the required .NET version from 3.0 to 3.1

Second, I'm receiving the error below while trying to compile the project:

Extensions/ServiceCollectionExtensions.cs(54,52): error CS0246: The type or namespace name 'TranslatorMicroservice' could not be found (are you missing a using directive or an assembly reference?) [/home/web/public_html/_tools/bot/src/TgTranslator.csproj]
Exceptions/InvalidSettingValueException.cs(5,18): warning RCS1194: Implement exception constructors. [/home/web/public_html/_tools/bot/src/TgTranslator.csproj]
Exceptions/UnauthorizedSettingChangingException.cs(5,18): warning RCS1194: Implement exception constructors. [/home/web/public_html/_tools/bot/src/TgTranslator.csproj]
Exceptions/UnsupportedCommand.cs(5,18): warning RCS1194: Implement exception constructors. [/home/web/public_html/_tools/bot/src/TgTranslator.csproj]
Exceptions/UnsupportedMenuItem.cs(5,18): warning RCS1194: Implement exception constructors. [/home/web/public_html/_tools/bot/src/TgTranslator.csproj]

**Comment by Dubzer** [comment]
Thanks for the reporting! I don't know how it leaked, but I fixed it in the latest commit. I also updated readme to match .NET Core version and used DB

**Comment by SamAriafar** [comment]
Still you haven't fixed the error with _TranslatorMicroservice_

**Comment by SamAriafar** [comment]
Still, you haven't fixed the error with _TranslatorMicroservice_.
